### ISSUE TITLE
```upload_protocol`` option ignored in platformio.ini

### ISSUE THREAD

**Issue by pelikhan** [platformio/platform-atmelsam#3]
See https://github.com/platformio/platformio-core/issues/845#issuecomment-264307879

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-atmelsam/releases/tag/v1.2.1

1. Please update local copy of development platform via `pio update`
2. You need the [latest development version](http://docs.platformio.org/en/stable/installation.html#development-version) of PlatformIO 3.2 (is planned for release next week)
3. Set `upload_protocol = stk500v2` in Project Configuration File and run this command
```
pio run -t buildprog
```

You should receive final HEX.
